---
- name: Install Apache, PHP
  vars:
    packages:
      - apache2
      - php
      - php-mysql
      - mariadb-client
  apt:
    pkg: "{{ packages }}"
    update_cache: yes
    state: latest

- name: Copy Adminer
  copy:
    src: adminer.php
    dest: /var/www/html/adminer.php