---
# This playbook will set up an EC2 instance with a tag of Name = proxysql
# It will install Proxysql with a hostgroup, host and user created by other steps in this project
- hosts: all

  gather_facts: no

  become: yes

  user: ubuntu

  vars:
    proxysql_admin_password: admin
    proxysql_monitor_password: monitorpassword
    # look up the RDS instance details from AWS Secrets Manager
    rds_details: "{{ lookup('aws_secret', 'rds') }}"

  roles:
    - proxysql
