---
- hosts: all

  gather_facts: no

  become: yes

  user: ubuntu

  vars:
    proxysql_admin_password: admin
    proxysql_monitor_password: monitorpassword
    # look up the RDS instance details from AWS Secrets Manager
    rds_details: "{{ lookup('aws_secret', 'rds') }}"

  roles:
    - proxysql