# Any changes here means ProxySQL must be restarted
# https://github.com/sysown/proxysql/wiki/Global-variables

- name: Set interfaces
  proxysql_global_variables:
    login_user: "admin"
    login_password: "{{ proxysql_admin_password }}"
    variable: "mysql-interfaces"
    value: "0.0.0.0:3306;/var/lib/proxysql/proxysql.sock"
  notify:
    - Restart proxysql

- name: Set desired number of threads (should match number of CPUs)
  proxysql_global_variables:
    login_user: "admin"
    login_password: "{{ proxysql_admin_password }}"
    variable: "mysql-threads"
    value: "2"
  notify:
    - Restart proxysql

- name: Set max connections
  proxysql_global_variables:
    login_user: "admin"
    login_password: "{{ proxysql_admin_password }}"
    variable: "mysql-max_connections"
    value: "1000"
  notify:
    - Restart proxysql

- name: Set timeout
  proxysql_global_variables:
    login_user: "admin"
    login_password: "{{ proxysql_admin_password }}"
    variable: "mysql-long_query_time"
    value: "1000"
  notify:
    - Restart proxysql

- name: Set monitor username
  proxysql_global_variables:
    login_user: "admin"
    login_password: "{{ proxysql_admin_password }}"
    variable: "mysql-monitor_username"
    value: "proxymonitor"
  notify:
    - Restart proxysql

- name: Set monitor password
  proxysql_global_variables:
    login_user: "admin"
    login_password: "{{ proxysql_admin_password }}"
    variable: "mysql-monitor_password"
    value: "{{ proxysql_monitor_password }}"
  notify:
    - Restart proxysql

- name: Set monitor interval to 30s
  proxysql_global_variables:
    login_user: "admin"
    login_password: "{{ proxysql_admin_password }}"
    variable: "mysql-monitor_connect_interval"
    value: "30000"
  notify:
    - Restart proxysql

# Logging stuff
# https://github.com/sysown/proxysql/wiki/Query-Logging

- name: Log file name
  proxysql_global_variables:
    login_user: "admin"
    login_password: "{{ proxysql_admin_password }}"
    variable: "mysql-eventslog_filename"
    value: "queries.log"
  notify:
    - Restart proxysql

- name: Set logging format to JSON
  proxysql_global_variables:
    login_user: "admin"
    login_password: "{{ proxysql_admin_password }}"
    variable: "mysql-eventslog_format"
    value: "2"
  notify:
    - Restart proxysql

- name: Enable logging globally
  proxysql_global_variables:
    login_user: "admin"
    login_password: "{{ proxysql_admin_password }}"
    variable: "mysql-eventslog_default_log"
    value: "1"
  notify:
    - Restart proxysql

- name: Rules to log ALL queries
  proxysql_query_rules:
    login_user: "admin"
    login_password: "{{ proxysql_admin_password }}"
    apply: no
    active: 1
    state: present
    rule_id: "1"
    match_digest: "."
    log: "1"
    load_to_runtime: True
